spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://gangajikimi-db.cjsgei08gb4x.ap-northeast-2.rds.amazonaws.com:5432/postgres
    username: postgres
    password: gangajikimi1234
    driver-class-name: org.postgresql.Driver
    sql:
      init:
        mode: never
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis
      port: 6379
  cache:
    type: redis
jwt:
  access:
    secretKey: gangajikimibimilkeyjironggaebalgeumanhagosibda
    expiration: 600000 # 10분
  refresh:
    expiration: 1209600000 # 14주

logging:
  level:
    org.hibernate.type: trace
    org.springframework.security: debug
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
    multipart:
      max-file-size: 5MB
      max-request-size: 25MB
cloud:
  aws:
    s3:
      bucket: gangajikimi-server   # 버킷 이름
    region: ap-northeast-2          # 서울 리전

gemini:
  api:
    url: "https://generativelanguage.googleapis.com"
    key: AQ.Ab8RN6JeFsKpjlxQ9zGLVBungwkdoiODF-Zl7dyphbdF_V8Czg
    model: gemini-1.5-flash

  ai:
    vertex:
      ai:
        gemini:
          # Google Cloud 프로젝트 ID
          project-id: 'YOUR_PROJECT_ID'
          # 사용할 지역
          location: 'us-central1'
          # 사용할 모델
          model: 'gemini-1.5-pro-preview-0409'
          # API 키 (환경 변수에서 가져오는 것을 권장)